### ISSUE TITLE
CVE是不是写错了

### ISSUE THREAD

**Issue by hazzel-cn** [Qclover/Gitlab_RCE_CVE_2021_2205#1]
2205是Oracle的洞，gitlab的是22205吧

**Comment by Qclover** [comment]
感谢提醒、已纠正



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Haozhe ***@***.***&gt;
发送时间: 2021年11月2日 02:53
收件人: Qclover/Gitlab_RCE_CVE_2021_2205 ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[Qclover/Gitlab_RCE_CVE_2021_2205] CVE是不是写错了 (Issue #1)





 
2205是Oracle的洞，gitlab的是22205吧
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
